### ISSUE TITLE
Error in installing Snob2

### ISSUE THREAD

**Issue by Scinawa** [risi-kondor/Snob2#7]
Hello again Risi, 

I encounter an error (pasted below) while installing Snob2. 
The problem is a file not found:

`../include/Snob2_base.cpp: No such file or directory.`

It is strange, as in the setup.py the directory ../include is correctly included in the project. 
This is the error:

llowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /hpctmp/classicwuongo/envs/sage310/bin/x86_64-conda-linux-gnu-c++ -MMD -MF /home/svu/cccales/Snob2/python/build/temp.linux-x86_64-cpython-310/bindings/Snob2_bindings.o.d -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /hpctmp/classicwuongo/envs/sage310/include -fPIC -O2 -isystem /hpctmp/classicwuongo/envs/sage310/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /hpctmp/classicwuongo/envs/sage310/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /hpctmp/classicwuongo/envs/sage310/include -fPIC -I../../cnine -I../../cnine/include -I../../cnine/modules -I../../cnine/combinatorial -I../../cnine/containers -I../../cnine/math -I../../cnine/objects/backendA -I../../cnine/objects/backendB -I../../cnine/objects/scalar -I../../cnine/objects/tensor -I../../cnine/objects/tensor_views -I../../cnine/objects/tensor_views/functions -I../include -I../combinatorial -I../Sn -I/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include -I/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/TH -I/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/THC -I/hpctmp/classicwuongo/envs/sage310/include/python3.10 -c -c /home/svu/cccales/Snob2/python/bindings/Snob2_bindings.cpp -o /home/svu/cccales/Snob2/python/build/temp.linux-x86_64-cpython-310/bindings/Snob2_bindings.o -std=c++14 -Wno-sign-compare -Wno-deprecated-declarations -Wno-unused-variable -Wno-reorder -Wno-reorder-ctor -Wno-overloaded-virtual -D_WITH_ATEN -DCNINE_RANGE_CHECKING -DCNINE_SIZE_CHECKING -DCNINE_DEVICE_CHECKING -DWITH_FAKE_GRAD -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=snob_base -D_GLIBCXX_USE_CXX11_ABI=0
FAILED: /home/svu/cccales/Snob2/python/build/temp.linux-x86_64-cpython-310/bindings/Snob2_bindings.o
/hpctmp/classicwuongo/envs/sage310/bin/x86_64-conda-linux-gnu-c++ -MMD -MF /home/svu/cccales/Snob2/python/build/temp.linux-x86_64-cpython-310/bindings/Snob2_bindings.o.d -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /hpctmp/classicwuongo/envs/sage310/include -fPIC -O2 -isystem /hpctmp/classicwuongo/envs/sage310/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /hpctmp/classicwuongo/envs/sage310/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /hpctmp/classicwuongo/envs/sage310/include -fPIC -I../../cnine -I../../cnine/include -I../../cnine/modules -I../../cnine/combinatorial -I../../cnine/containers -I../../cnine/math -I../../cnine/objects/backendA -I../../cnine/objects/backendB -I../../cnine/objects/scalar -I../../cnine/objects/tensor -I../../cnine/objects/tensor_views -I../../cnine/objects/tensor_views/functions -I../include -I../combinatorial -I../Sn -I/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include -I/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/TH -I/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/THC -I/hpctmp/classicwuongo/envs/sage310/include/python3.10 -c -c /home/svu/cccales/Snob2/python/bindings/Snob2_bindings.cpp -o /home/svu/cccales/Snob2/python/build/temp.linux-x86_64-cpython-310/bindings/Snob2_bindings.o -std=c++14 -Wno-sign-compare -Wno-deprecated-declarations -Wno-unused-variable -Wno-reorder -Wno-reorder-ctor -Wno-overloaded-virtual -D_WITH_ATEN -DCNINE_RANGE_CHECKING -DCNINE_SIZE_CHECKING -DCNINE_DEVICE_CHECKING -DWITH_FAKE_GRAD -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=snob_base -D_GLIBCXX_USE_CXX11_ABI=0
**/home/svu/cccales/Snob2/python/bindings/Snob2_bindings.cpp:17:10: fatal error: ../include/Snob2_base.cpp: No such file or directory**
   17 | #include "../include/Snob2_base.cpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/hpctmp/classicwuongo/envs/sage310/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

---------------------------

I take this opportunity to signal that:
- the doc (https://risi-kondor.github.io/Snob2/) should be updated as there is no `setup.sty` file anymore, but setup.py
- there is a warning suggesting to deprecate `python setup.py install`

This is the warning at about `python setup.py install`

----------
python setup.py install
running install
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************
classic

**Comment by risi-kondor** [comment]
I've been doing quite a lot of reorganizing in Snob2 in the last few days, I'll take a look and see if maybe something got messed up.

**Comment by Scinawa** [comment]
Thank you!

**Comment by Scinawa** [comment]
So, taking the hint that you changed a few things in the past days, I checked out the commit dadd66ac805b5b03d08a18916bfa20071ee3eca5 and indeed the error is different: 

**c++: error: unrecognized command line option '-std=c++14'**

This is due to the version of gcc that I am using, which does not support this parameter for c++14. If I change the setup.py line  with `-std=c++1y` for backward compatibility the error is different, but further errors about the compilation of pytorch prevents me from installing Snob2.

**Comment by risi-kondor** [comment]
I just checked and on my machine it installs fine. As far as I understand `c++1y` is a partial implementation of c++14, but I really only use some minimal c++14 functionality (actually the newer tensor classes will use some c++17, but we can cross that bridge when we get to it) so hopefully `c++1y` will be sufficient. Can you send me the errors that you are getting now?

**Comment by Scinawa** [comment]
Same thing:

**/home/svu/cqtales/Snob2/python/bindings/Snob2_bindings.cpp:17:10: fatal error: Snob2_base.cpp: No such file or directory
   17 | #include "Snob2_base.cpp"**
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/hpctmp/cccwuongo/envs/sage310/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/hpctmp/cccwuongo/envs/sage310/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by risi-kondor** [comment]
This might be very simple. Does the `cnine_root` variable in `setup.py` point to the root of the `cnine` source directory on your system? (The documentation mentions this.) You need this because Snob2 needs to directly access the `cnine` header files. By default `cnine_root` is `../../cnine` so if you cloned `cnine` and `Snob2` side by side into the same directory, the default should be fine.

The more conventional way of doing things would be of course for `cnine` to install its headers in some place like `/usr/local/include` but I decided not to do this because the software is still in the experimental phase. 

It is also possible that the directory search path got messed up in some other way because I actually changed `setup.py` a few days ago to make it more streamlined. Previously it involved `os.getcwd()` but that seemed redundant. Maybe on some systems it is required though, I am not sure, so I'd love to know what needs to be done to resolve your problem. According to your original message `-I../../cnine/include` is indeed part of the command issued to `gcc`.

**Comment by Scinawa** [comment]
Yes, it does.
I also tried to change `setup.py` with the `getcwd` command you left commented, and also using an hardcoded path to the `cnine` directory (which is in the correct location), and I get the same error, thinking that the problem might be caused by the use of virtual environments. 

Maybe I can help more if I understand why you think this problem is related to cnine? It seems that there is a problem with finding `Snob2_base.cpp` inside the `Snob2_bindings.cpp` file. 

/home/svu/cqtales/Snob2/python/bindings/Snob2_bindings.cpp:17:10: fatal error: Snob2_base.cpp: No such file or directory
   17 | #include "Snob2_base.cpp"
      |          ^~~~~~~~~~~~~~~~

**Comment by risi-kondor** [comment]
Sorry, I misread, I thought it was `Cnine_base.cpp` that the compiler cant find. This is even more weird. Let me think about what we can do, wonder if other people are also running into a version of this problem. It seems like such a trivial issue.

**Comment by risi-kondor** [comment]
I changed back to absolute paths using `os.getcwd()` and I think it will probably work for you now. My guess is that relative paths work fine for stand-alone python installations but for some reason not for environments like Conda. Could you please give it another shot? Thanks.

**Comment by Scinawa** [comment]
Thanks, it works now. 


Did you change the import name from Snob2 (which worked in some previous code I have)  to snob? 

```
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import snob
Snob2 initialized.

>>> import Snob2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Snob2'
```

Thank you!




There are a few warnings here and there, which I attach FYI. 
(sage310) [ale@atlas8-c01 python]$ python setup.py install

running install
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing src/snob.egg-info/PKG-INFO
writing dependency_links to src/snob.egg-info/dependency_links.txt
writing top-level names to src/snob.egg-info/top_level.txt
reading manifest file 'src/snob.egg-info/SOURCES.txt'
writing manifest file 'src/snob.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'snob_base' extension
Emitting ninja build file /home/svu/ale/Snob2/python/build/temp.linux-x86_64-cpython-310/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /hpctmp/classicwuongo/envs/sage310/bin/x86_64-conda-linux-gnu-c++ -MMD -MF /home/svu/ale/Snob2/python/build/temp.linux-x86_64-cpython-310/bindings/Snob2_bindings.o.d -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /hpctmp/classicwuongo/envs/sage310/include -fPIC -O2 -isystem /hpctmp/classicwuongo/envs/sage310/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /hpctmp/classicwuongo/envs/sage310/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /hpctmp/classicwuongo/envs/sage310/include -fPIC -I/home/svu/ale/Snob2/python/../../cnine -I/home/svu/ale/Snob2/python/../../cnine/include -I/home/svu/ale/Snob2/python/../../cnine/modules -I/home/svu/ale/Snob2/python/../../cnine/combinatorial -I/home/svu/ale/Snob2/python/../../cnine/containers -I/home/svu/ale/Snob2/python/../../cnine/math -I/home/svu/ale/Snob2/python/../../cnine/objects/backendA -I/home/svu/ale/Snob2/python/../../cnine/objects/backendB -I/home/svu/ale/Snob2/python/../../cnine/objects/scalar -I/home/svu/ale/Snob2/python/../../cnine/objects/tensor -I/home/svu/ale/Snob2/python/../../cnine/objects/tensor_views -I/home/svu/ale/Snob2/python/../../cnine/objects/tensor_views/functions -I/home/svu/ale/Snob2/python/../include -I/home/svu/ale/Snob2/python/../combinatorial -I/home/svu/ale/Snob2/python/../Sn -I/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include -I/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/TH -I/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/THC -I/hpctmp/classicwuongo/envs/sage310/include/python3.10 -c -c /home/svu/ale/Snob2/python/bindings/Snob2_bindings.cpp -o /home/svu/ale/Snob2/python/build/temp.linux-x86_64-cpython-310/bindings/Snob2_bindings.o -std=c++17 -Wno-sign-compare -Wno-deprecated-declarations -Wno-unused-variable -Wno-reorder -Wno-reorder-ctor -Wno-overloaded-virtual -D_WITH_ATEN -DCNINE_RANGE_CHECKING -DCNINE_SIZE_CHECKING -DCNINE_DEVICE_CHECKING -DWITH_FAKE_GRAD -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=snob_base -D_GLIBCXX_USE_CXX11_ABI=0
In file included from /home/svu/ale/Snob2/python/../combinatorial/CombinatorialBankLevel.hpp:16,
                 from /home/svu/ale/Snob2/python/../combinatorial/CombinatorialBank.hpp:15,
                 from /home/svu/ale/Snob2/python/../combinatorial/CombinatorialClasses.hpp:15,
                 from /home/svu/ale/Snob2/python/../include/Snob2_session.hpp:16,
                 from /home/svu/ale/Snob2/python/bindings/Snob2_bindings.cpp:18:
/home/svu/ale/Snob2/python/../combinatorial/IntegerPartition.hpp: In member function 'Snob2::IntegerPartition& Snob2::IntegerPartition::add(int, int)':
/home/svu/ale/Snob2/python/../combinatorial/IntegerPartition.hpp:165:7: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
  165 |       for(int i=0; i<k; i++) newp[i]=p[i]; newp[k]=m;
      |       ^~~
/home/svu/ale/Snob2/python/../combinatorial/IntegerPartition.hpp:165:44: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'for'
  165 |       for(int i=0; i<k; i++) newp[i]=p[i]; newp[k]=m;
      |                                            ^~~~
In file included from /home/svu/ale/Snob2/python/../../cnine/modules/cnine/containers:6,
                 from /home/svu/ale/Snob2/python/../Sn/SnIrrepObj.hpp:14,
                 from /home/svu/ale/Snob2/python/../Sn/SnObj.hpp:21,
                 from /home/svu/ale/Snob2/python/../Sn/SnBank.hpp:15,
                 from /home/svu/ale/Snob2/python/../include/Snob2_session.hpp:18:
/home/svu/ale/Snob2/python/../../cnine/include/../containers/associative_container.hpp: In member function 'int cnine::associative_container_iterator<KEY, OBJ>::dummy() const':
/home/svu/ale/Snob2/python/../../cnine/include/../containers/associative_container.hpp:112:23: warning: no return statement in function returning non-void [-Wreturn-type]
  112 |     int dummy() const{}
      |                       ^
In file included from /hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/torch/csrc/Exceptions.h:14,
                 from /hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/python.h:11,
                 from /hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/torch/extension.h:6,
                 from /hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:6,
                 from /home/svu/ale/Snob2/python/bindings/Snob2_bindings.cpp:11:
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::Permutation>':
/home/svu/ale/Snob2/python/bindings/Snob2_bindings.cpp:59:60:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::Permutation>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
 1479 | class class_ : public detail::generic_type {
      |       ^~~~~~
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::IntegerPartition>':
/home/svu/ale/Snob2/python/bindings/Snob2_bindings.cpp:88:70:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::IntegerPartition>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::IntegerPartitions>':
/home/svu/ale/Snob2/python/bindings/Snob2_bindings.cpp:102:74:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::IntegerPartitions>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::YoungTableau>':
/home/svu/ale/Snob2/python/bindings/Snob2_bindings.cpp:127:50:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::YoungTableau>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::StandardYoungTableaux>':
/home/svu/ale/Snob2/python/bindings/Snob2_bindings.cpp:151:67:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::StandardYoungTableaux>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::SnElement>':
/home/svu/ale/Snob2/python/bindings/SnClasses_py.cpp:12:51:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::SnElement>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::SnCClass>':
/home/svu/ale/Snob2/python/bindings/SnClasses_py.cpp:40:29:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::SnCClass>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::SnCharacter>':
/home/svu/ale/Snob2/python/bindings/SnClasses_py.cpp:54:43:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::SnCharacter>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::SnIrrep>':
/home/svu/ale/Snob2/python/bindings/SnClasses_py.cpp:67:43:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::SnIrrep>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::SnClassFunction>':
/home/svu/ale/Snob2/python/bindings/SnClasses_py.cpp:90:26:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::SnClassFunction>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::Sn>':
/home/svu/ale/Snob2/python/bindings/SnClasses_py.cpp:118:30:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::Sn>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::SnType>':
/home/svu/ale/Snob2/python/bindings/SnClasses_py.cpp:157:44:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::SnType>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::SnFunction>':
/home/svu/ale/Snob2/python/bindings/SnFunctions_py.cpp:15:20:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::SnFunction>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::SnOverSmFunction>':
/home/svu/ale/Snob2/python/bindings/SnFunctions_py.cpp:63:23:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::SnOverSmFunction>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::SnPart>':
/home/svu/ale/Snob2/python/bindings/SnFunctions_py.cpp:98:35:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::SnPart>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::SnVec>':
/home/svu/ale/Snob2/python/bindings/SnFunctions_py.cpp:124:25:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::SnVec>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h: In instantiation of 'class pybind11::class_<Snob2::ClausenFFT>':
/home/svu/ale/Snob2/python/bindings/SnFFT_py.cpp:12:19:   required from here
/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:1479:7: warning: 'pybind11::class_<Snob2::ClausenFFT>' declared with greater visibility than its base 'pybind11::detail::generic_type' [-Wattributes]
At global scope:
cc1plus: note: unrecognized command-line option '-Wno-reorder-ctor' may have been intended to silence earlier diagnostics
/hpctmp/classicwuongo/envs/sage310/bin/x86_64-conda-linux-gnu-c++ -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/hpctmp/classicwuongo/envs/sage310/lib -Wl,-rpath-link,/hpctmp/classicwuongo/envs/sage310/lib -L/hpctmp/classicwuongo/envs/sage310/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/hpctmp/classicwuongo/envs/sage310/lib -Wl,-rpath-link,/hpctmp/classicwuongo/envs/sage310/lib -L/hpctmp/classicwuongo/envs/sage310/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/hpctmp/classicwuongo/envs/sage310/lib -Wl,-rpath-link,/hpctmp/classicwuongo/envs/sage310/lib -L/hpctmp/classicwuongo/envs/sage310/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /hpctmp/classicwuongo/envs/sage310/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /hpctmp/classicwuongo/envs/sage310/include /home/svu/ale/Snob2/python/build/temp.linux-x86_64-cpython-310/bindings/Snob2_bindings.o -L/hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-cpython-310/snob_base.cpython-310-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-cpython-310/snob_base.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/snob
copying build/lib.linux-x86_64-cpython-310/snob/__init__.py -> build/bdist.linux-x86_64/egg/snob
copying build/lib.linux-x86_64-cpython-310/snob/SnFunction.py -> build/bdist.linux-x86_64/egg/snob
byte-compiling build/bdist.linux-x86_64/egg/snob/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/snob/SnFunction.py to SnFunction.cpython-310.pyc
creating stub loader for snob_base.cpython-310-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/snob_base.py to snob_base.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/snob.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/snob.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/snob.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/snob.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/snob.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/snob-0.0.0-py3.10-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing snob-0.0.0-py3.10-linux-x86_64.egg
creating /hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/snob-0.0.0-py3.10-linux-x86_64.egg
Extracting snob-0.0.0-py3.10-linux-x86_64.egg to /hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages
Adding snob 0.0.0 to easy-install.pth file

Installed /hpctmp/classicwuongo/envs/sage310/lib/python3.10/site-packages/snob-0.0.0-py3.10-linux-x86_64.egg
Processing dependencies for snob==0.0.0
Finished processing dependencies for snob==0.0.0

**Comment by risi-kondor** [comment]
Thanks! Yes, I changed the import name to just `snob` thinking (maybe mistaknely) caps are not inline with python convention. I need to change the docs to reflect this. Thanks for all the compiler warnings, I'll go through them and see which ones are worth worrying about.

**Comment by Scinawa** [comment]
Yes I agree that snob is more PEP8 than Snob2 :)

Thanks again.
Ale.
